---
# tasks file for conf-webserver
- name: Installing Apache Web Server (httpd)
  package:
    name: httpd
    state: present

- name: Copying webpage
  copy:
    content: "<h1>Configured by Ansible</h1>\n <h2>Premchand</h2>{{ ansible_hostname }}"
    dest: "/var/www/html/index.html"
    mode: 644

- name: Enabling and starting the web server
  service:
    name: "httpd"
    state: started
    enabled: yes
